DROP TABLE IF EXISTS host;

CREATE TABLE host (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT      NOT NULL,
	password TEXT      NOT NULL,
	hostname TEXT      NOT NULL UNIQUE,
	ip       TEXT,
	changed  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
